### ISSUE TITLE
Add pagination to the home page

### ISSUE THREAD

**Issue by blopker** [hotwire-django/hotwire-django-realworld#13]
After a `./manage createdata 100` the home page loads pretty slowly. This ticket is to add pagination to the article lists. This includes on the homepage and on the profile details page.

**Comment by C4ptainCrunch** [comment]
It's a N+1 query problem: The view loads a list of [articles](https://github.com/hotwire-django/hotwire-django-realworld/blob/main/home/views.py#L11) and the template makes a new query for each article to [get the username](https://github.com/hotwire-django/hotwire-django-realworld/blob/main/templates/articles/list.html#L12). I'll fix that with a `select_related`

Edit: It might even be a 2N+1 problem as we also fetch the [favourite count](https://github.com/hotwire-django/hotwire-django-realworld/blob/main/templates/articles/list.html#L17). I'll also add django-debug-toolbar in a PR so we can inspect those queries.

**Comment by blopker** [comment]
Thank you! I still think we need pagination though, just so users don't have an endless list of content.
