### ISSUE TITLE
Article detail page

### ISSUE THREAD

**Issue by blopker** [hotwire-django/hotwire-django-realworld#3]
This ticket is to implement the article detail page like https://demo.realworld.io/#/article/hi-ox1ksi

The template is in `templates/article/detail.html`.

The URL should be `/article/{article.slug}`.

This includes making comments work.

**Comment by chrisgrande** [comment]
Comments view, adding, deleting up and running. Need to do editing, validation on delete. 

Uses some simple turbo-frames at the moment without anything really special so some interactions aren't correct.

https://user-images.githubusercontent.com/825577/103953072-738e5880-510f-11eb-89d5-4f88ec04d2ec.mov

**Comment by SeringeSylla** [comment]
ok
