### ISSUE TITLE
Allow users to add tags to their articles

### ISSUE THREAD

**Issue by blopker** [hotwire-django/hotwire-django-realworld#7]
On the article create/edit page add an extra field where the user can add tags to their article.

As far as I can tell on the demo app users can input a comma (or space?) separated list of tags. If the tag exists, it's added to the article object. If it doesn't it's created first then added.

**Comment by luanfonceca** [comment]
Hi @blopker I'm getting this one, okay?

**Comment by blopker** [comment]
Sounds good! Thank you.
